# Generated by Django 2.2.24 on 2021-08-16 13:36

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetail',
            name='tz1',
            field=timezone_field.fields.TimeZoneField(blank=True, default='Asia/Calcutta', null=True),
        ),
    ]
