# Generated by Django 2.2.24 on 2021-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210816_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdetail',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
