# Generated by Django 2.2.24 on 2021-08-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_shiftdetail_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdetail',
            name='job',
            field=models.CharField(choices=[('Customer 1', 'Customer 1'), ('Project A', 'Project A'), ('Shift Manager', 'Shift Manager'), ('Work site A', 'Work site A')], max_length=50, null=True),
        ),
    ]
