# Generated by Django 3.2.6 on 2021-09-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210831_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='vender_profile',
            new_name='vendor_profile',
        ),
    ]
