# Generated by Django 2.2.24 on 2021-09-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210906_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
