# Generated by Django 2.2.24 on 2021-09-06 09:54

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200, null=True)),
                ('date1', models.DateField()),
                ('start_time1', models.TimeField(null=True)),
                ('end_time1', models.TimeField(null=True)),
                ('location1', models.CharField(max_length=200, null=True)),
                ('tz11', timezone_field.fields.TimeZoneField(blank=True, default='Asia/Calcutta', null=True)),
                ('username1', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
