# Generated by Django 2.2.24 on 2021-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_template_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='note',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
