# Generated by Django 2.2.24 on 2021-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_template_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetail',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
