# Generated by Django 2.2.24 on 2021-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210907_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdetail',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='text1',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
